import type { Metadata } from "next";
import "prismjs/themes/prism-tomorrow.css";
import "react-notion-components/dist/style.css";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<div className="px-4">{children}</div>
			</body>
		</html>
	);
}
